# Introduction to Numpy

### Author: Srushti Shimpi

[LinkedIn Profile](https://www.linkedin.com/in/srushti-shimpi77/)

In [345]:
#importing numpy library
import numpy as np

# File importing using numpy

In [346]:
# Importing data from text file
np.genfromtxt("data.txt", delimiter='\t')

# Importing data from CSV file
np.genfromtxt('data.csv',delimiter=',')


array([[ nan,  nan,  nan,  nan,  nan,  nan],
       [101.,   1.,   2.,  64.,   0.,   1.],
       [101.,   1.,   2.,  64.,   0.,   2.],
       ...,
       [219.,   2.,   1.,  61.,   2.,   4.],
       [219.,   2.,   1.,  61.,   1.,   5.],
       [219.,   2.,   1.,  61.,   0.,   6.]])

# Creating Arrays using numpy

In [347]:
np.array([1,2,3]) #One dimensional array
np.array([(1,2,3),(4,5,6)]) # Two dimensional array
np.zeros(5) # 1D array of length 5 all values 0
np.ones((3,4)) # 3x4 array with all values 1
np.eye(4) #4x4 array of 0 with 1 on diagonal (Identity matrix)
np.linspace(0,50,7) # Array of 7 evenly divided values from 0 to 50
np.full((2,3),8) # 2x3 array with all values 8
np.random.rand(4,5) # 4x5 array of random floats between 0–1
np.random.rand(3,4)*100 # 3x4 array of random floats between 0–100
np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4

array([[3, 4, 4],
       [0, 2, 0]])

In [348]:
np.array([1,2,3]) #One dimensional array

array([1, 2, 3])

In [349]:
np.array([(1,2,3),(4,5,6)]) # Two dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [350]:
np.zeros(5) # 1D array of length 5 all values 0

array([0., 0., 0., 0., 0.])

In [351]:
np.ones((3,4)) # 3x4 array with all values 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [352]:
np.eye(4) #4x4 array of 0 with 1 on diagonal (Identity matrix)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [353]:
np.linspace(0,50,7) # Array of 7 evenly divided values from 0 to 50

array([ 0.        ,  8.33333333, 16.66666667, 25.        , 33.33333333,
       41.66666667, 50.        ])

In [354]:
np.full((2,3),8) # 2x3 array with all values 8

array([[8, 8, 8],
       [8, 8, 8]])

In [355]:
np.random.rand(4,5) # 4x5 array of random floats between 0–1

array([[0.79268432, 0.63183991, 0.46754632, 0.08198261, 0.79423845],
       [0.01617528, 0.6819544 , 0.78749885, 0.32506115, 0.29648234],
       [0.82564684, 0.9100363 , 0.47981453, 0.21423234, 0.21701659],
       [0.78528531, 0.29222826, 0.86217926, 0.43670357, 0.13676292]])

In [356]:
np.random.rand(3,4)*100 # 3x4 array of random floats between 0–100

array([[36.72230212, 70.22182464, 41.61097365, 51.57460028],
       [15.21146397, 77.35245245, 13.97069611,  1.07009476],
       [13.99478759, 34.12175235, 45.9925684 , 33.53947866]])

In [357]:
np.random.randint(5,size=(2,3)) # 2x3 array with random ints between 0–4

array([[0, 2, 2],
       [3, 3, 3]])

# Inspecting properties using numpy

In [358]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [359]:
arr.size  #Returns number of elements in arr

8

In [360]:
arr.shape #Returns dimensions of arr (rows,columns)

(2, 4)

In [361]:
arr.dtype #Returns type of elements in arr

dtype('int32')

In [362]:
arr.astype('float64') #Convert arr elements to type float64

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [363]:
arr.tolist() #Convert arr to a Python list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [364]:
np.info(np.eye) #View documentation for np.eye

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

# Copying, sorting and reshaping using numpy

In [365]:
np.copy(arr) #Copies arr to new memory

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [366]:
arr.view('float64') #Creates view of arr elements with type dtype

array([[4.24399158e-314, 8.48798317e-314],
       [1.27319747e-313, 1.69759663e-313]])

In [367]:
arr.sort()  #Sorts arr

In [368]:
arr.sort(axis=0) #Sorts specific axis of arr

In [369]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr2.flatten() #Flattens 2D array to 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [370]:
arr.T #Transposes arr (rows become columns and vice versa)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [371]:
arr.reshape(4,2) #Reshapes arr to 4 rows, 2 columns without changing data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [372]:
arr.resize((2,4)) #Changes arr shape to 2x4 and fills new values with 0

# Adding or removing elements using numpy

In [373]:
np.append(arr, [7,8,9,10]) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  7,  8,  9, 10])

In [374]:
np.insert(arr,2,[7,9]) #Inserts values into arr before index 2

array([1, 2, 7, 9, 3, 4, 5, 6, 7, 8])

In [375]:
np.delete(arr,1,0)  #Deletes column on index 4 of arr

array([[1, 2, 3, 4]])

# Combining and splitting

In [376]:
a1 = np.array([1,3])
a2 = np.array([4,6])

a3 = np.concatenate((a1,a2),axis=0) #Adds a2 as rows to the end of a1
print(a3)

[1 3 4 6]


In [377]:
np.split(arr,2) #Splits arr into 2 sub-arrays

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [378]:
np.hsplit(arr,2) #Splits arr horizontally on the 2th index

[array([[1, 2],
        [5, 6]]), array([[3, 4],
        [7, 8]])]

# Indexing, slicing and subsetting

In [379]:
x = [1,2,3,4,5,6,7,8,9,0,10,15]
x[5] #Returns the element at index 5

6

In [380]:
x[1]=4 #Assigns array element on index 1 the value 4
x[1]

4

In [381]:
x[0:3] #Returns the elements at indices 0,1,2 (On a 2D array: returns rows 0,1,2)


[1, 4, 3]

In [382]:
x[:2] #Returns the elements at indices 0,1 (On a 2D array: returns rows 0,1)

[1, 4]

# Scalar Math

In [383]:
ar = [5,6,7,2,6]
np.add(ar,1) #Add 1 to each array element

array([6, 7, 8, 3, 7])

In [384]:
np.subtract(ar,2) #Subtract 2 from each array element

array([3, 4, 5, 0, 4])

In [385]:
np.multiply(ar,3) #Multiply each array element by 3

array([15, 18, 21,  6, 18])

In [386]:
np.divide(ar,4) #Divide each array element by 4 (returns np.nan for division by zero)

array([1.25, 1.5 , 1.75, 0.5 , 1.5 ])

In [387]:
np.power(ar,5) #Raise each array element to the 5th power

array([ 3125,  7776, 16807,    32,  7776], dtype=int32)

# Vector math

In [388]:
p = [1,2,3,4]
q = [5,6,7,8]

np.add(p,q) #Elementwise add q to p

array([ 6,  8, 10, 12])

In [389]:
np.subtract(p,q) #Elementwise subtract q from p

array([-4, -4, -4, -4])

In [390]:
np.multiply(p,q) #Elementwise multiply p by q

array([ 5, 12, 21, 32])

In [391]:
np.divide(p,q) #Elementwise divide p by q

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [392]:
np.power(p,q) #Elementwise raise p raised to the power of q

array([    1,    64,  2187, 65536], dtype=int32)

In [393]:
np.array_equal(p,q) #Returns True if the arrays have the same elements and shape

False

In [394]:
np.sqrt(ar) #Square root of each element in the array

array([2.23606798, 2.44948974, 2.64575131, 1.41421356, 2.44948974])

In [395]:
np.sin(ar) #Sine of each element in the array

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.90929743, -0.2794155 ])

In [396]:
np.log(ar) #Natural log of each element in the array

array([1.60943791, 1.79175947, 1.94591015, 0.69314718, 1.79175947])

In [397]:
np.abs(ar) #Absolute value of each element in the array

array([5, 6, 7, 2, 6])

In [398]:
np.ceil(ar) #Rounds up to the nearest int

array([5., 6., 7., 2., 6.])

In [399]:
np.floor(ar) #Rounds down to the nearest int

array([5., 6., 7., 2., 6.])

In [400]:
np.round(ar) #Rounds to the nearest int

array([5, 6, 7, 2, 6])

# Statistics

In [401]:
np.mean(ar,axis=0) #Returns mean along specific axis

5.2

In [402]:
np.sum(ar) #Returns sum of ar

26

In [403]:
np.amin(ar) #Returns minimum value of specific axis

2

In [404]:
np.amax(ar) #Returns maximum value of specific axis

7

In [405]:
np.var(ar) #Returns the variance of array

2.96

In [406]:
np.std(ar) #Returns the standard deviation of specific axis

1.7204650534085253

In [407]:
np.corrcoef(ar) #Returns correlation coefficient of array

1.0